Repository rocky-linux/peridot, pull requests merged in 2022-11, with the labels that each got.

#53 Postsubmit: Deploy impacted targets
  config/jobs/postsubmits.yaml
  config/jobs/presubmits.yaml
  hack/bazel_setup.sh
  hack/deploy_impacted.sh
  hack/frontend_build.sh
  hack/get_impacted_targets.sh
  rules_resf/defs.bzl
Labels: lgtm, approved

#54 Add comment (deploy test 1)
  apollo/impl/v1/server.go
Labels: lgtm, approved

#55 Add comment (deploy test 2)
  apollo/impl/v1/advisory.go
  hack/get_impacted_targets.sh
Labels: lgtm, approved

#56 Bump image version to v0.3.19 (Prow)
  apollo/impl/v1/advisory.go
  config/jobs/postsubmits.yaml
  config/jobs/presubmits.yaml
Labels: lgtm, approved

#57 Obsidian: Explain callbackForwarder
  obsidian/impl/v1/oauth2.go
Labels: lgtm, approved

#59 Fix impacted deploy (postsubmit)
  hack/get_impacted_targets.sh
Labels: lgtm, approved

#60 Prow should block PRs with merge commits
  config/prow/plugins.yaml
Labels: lgtm, approved

#58 Fix header wrapping in safari. Add tooltip to type/severity row icons
  apollo/ui/src/components/Overview.tsx
  apollo/ui/src/components/Root.tsx
  apollo/ui/src/components/ShowErrata.tsx
  apollo/ui/src/enumToText.tsx
Labels: lgtm, approved, ok-to-test

#62 Import RPM key to verify signature and stop blocking on failure
  peridot/keykeeper/v1/keywarming.go
  peridot/keykeeper/v1/sign.go
Labels: bug, lgtm, approved

#63 Fix Apollo skipping errata if failure happens after updating last sync
  apollo/workflow/poll_mirror_errata.go
Labels: lgtm, approved

#64 Upgrade srpmproc to v0.4.2
  go.mod
  go.sum
  vendor/github.com/rocky-linux/srpmproc/modulemd/modulemd.go
  vendor/github.com/rocky-linux/srpmproc/pkg/blob/file/file.go
  vendor/github.com/rocky-linux/srpmproc/pkg/blob/gcs/gcs.go
  vendor/github.com/rocky-linux/srpmproc/pkg/blob/s3/s3.go
  vendor/github.com/rocky-linux/srpmproc/pkg/data/import.go
  vendor/github.com/rocky-linux/srpmproc/pkg/data/process.go
  vendor/github.com/rocky-linux/srpmproc/pkg/data/utils.go
  vendor/github.com/rocky-linux/srpmproc/pkg/directives/add.go
  vendor/github.com/rocky-linux/srpmproc/pkg/directives/lookaside.go
  vendor/github.com/rocky-linux/srpmproc/pkg/directives/patch.go
  vendor/github.com/rocky-linux/srpmproc/pkg/directives/replace.go
  vendor/github.com/rocky-linux/srpmproc/pkg/directives/spec_change.go
  vendor/github.com/rocky-linux/srpmproc/pkg/misc/regex.go
  vendor/github.com/rocky-linux/srpmproc/pkg/modes/git.go
  vendor/github.com/rocky-linux/srpmproc/pkg/rpmutils/regex.go
  vendor/github.com/rocky-linux/srpmproc/pkg/srpmproc/fetch.go
  vendor/github.com/rocky-linux/srpmproc/pkg/srpmproc/patch.go
  vendor/github.com/rocky-linux/srpmproc/pkg/srpmproc/process.go
  vendor/modules.txt
Labels: lgtm, approved

#65 s3.kube_env should default to RESF Peridot bucket
  ci/s3.jsonnet
Labels: lgtm, approved

#66 Deploy objects with force_normal_tags should only apply
  ci/bazel.jsonnet
  rules_resf/defs.bzl
Labels: lgtm, approved

#67 Apollo: Keyword search now does pagination correctly
  apollo/db/psql/psql.go
Labels: lgtm, approved

#68 Peridot: Fix MakeActiveInRepo - Only set for current project
  peridot/builder/v1/workflow/yumrepofs.go
  peridot/db/db.go
  peridot/db/psql/package.go
Labels: lgtm, approved

#70 Module mode now correctly replaces all artifacts
  peridot/builder/v1/workflow/build.go
  peridot/builder/v1/workflow/module.go
  peridot/builder/v1/workflow/yumrepofs.go
  peridot/db/db.go
  peridot/db/psql/build.go
Labels: lgtm, approved
